controllers/SiteController.php
<?php namespace app\controllers;

use app\models\CompaniesInfo;
use app\models\Roles;
use app\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) {
            $dataProvider = new ActiveDataProvider([
                'query' => CompaniesInfo::find()
            ]);
            $isAdmin = Yii::$app->user->identity->isAdmin();
            return $this->render('index', ['dataProvider' => $dataProvider, 'isAdmin' => $isAdmin]);
        } else {
            return $this->redirect(Url::to(['site/login']));
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionUsers()
    {
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
            $users = User::find()->with('role')->all();
            return $this->render('users', ['users' => $users]);
        } else {
            return $this->redirect(Url::to(['site/login']));
        }
    }

    /**
     * @return bool
     * @throws NotFoundHttpException
     */
    public function actionUpdateUser()
    {
        $post = Yii::$app->request->post();
        $answer = false;
        if (Yii::$app->request->isAjax && isset($post['id'])) {
            $user = User::findOne($post['id']);
            if ($user) {
                $newLogin = trim($post['login']);
                $newPassword = trim($post['password']);
                $newRole = trim($post['role']);
                if ($newLogin && $user->login !== $newLogin) {
                    $user->login = $newLogin;
                }
                if ($newPassword && $user->password !== $newPassword) {
                    $user->password = $newPassword;
                }
                if ($newRole) {
                    $role = Roles::findOne(['name' => $newRole]);
                    if (!$role) {
                        return $answer;
                    } else {
                        if ($user->role_id !== $role->id) {
                            $user->role_id = $role->id;
                        }
                    }
                }
                $answer = $user->save();
            }
        } else {
            throw new NotFoundHttpException();
        }
        return $answer;
    }

    /**
     * @param int $id
     * @return bool|string
     * @throws NotFoundHttpException
     */
    public function actionUpdateCompany($id)
    {
        $post = Yii::$app->request->post();
        if (Yii::$app->request->isAjax && isset($post['id'])) {
            return self::updateCompanyInfo($post);
        } else if (!Yii::$app->user->isGuest) {
            $role = Yii::$app->user->identity->role->id;
            $model = CompaniesInfo::find()->where(['id' => $id])->one();
            if (!$model) {
                throw new NotFoundHttpException();
            }
            return $this->render('company', ['model' => $model, 'role' => $role]);
        } else {
            throw new NotFoundHttpException();
        }
    }

    /**
     * @param array $info
     * @return bool
    */
    public static function updateCompanyInfo($info)
    {
        $company = CompaniesInfo::findOne($info['id']);
        unset($info['id']);
        $answer = false;
        if ($company) {
            foreach ($info as $name => $value) {
                if ($value !== $company->$name) {
                    $company->$name = $value;
                }
            }
            $answer = $company->save();
        }
        return $answer;
    }
}

views/site/company.php
<?php

use app\models\CompaniesInfo;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\User;

/**
 * @var int $role
 * @var CompaniesInfo $model
 */

$this->title = $model->name;
$this->params['breadcrumbs'][] = $this->title;

?>
<div>
    <?php if ($role === User::ROLE_ADMIN) : ?>
        <?php $form = ActiveForm::begin([
            'options' => ['class' => 'update-user-form']
        ]); ?>
        <?= $form->field($model, 'name') ?>
        <?= $form->field($model, 'inn') ?>
        <?= $form->field($model, 'general_manager') ?>
        <?= $form->field($model, 'address') ?>

        <div class="form-group">
            <?= Html::button('Сохранить', ['class' => 'btn btn-success update-company-info', 'data-id' => $model->id]) ?>
        </div>
        <?php ActiveForm::end(); ?>
    <?php else : ?>
        <?php foreach ($model->attributes as $name => $value) { ?>
            <div class="themed-grid-col"><?= $name . ' = ' . $value ?></div>
        <?php } ?>
    <?php endif; ?>
</div>

views/site/error.php
<?php

/**
 * @var $this yii\web\View
 * @var $name string
 * @var $message string
 * @var $exception Exception
 */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Html;

/**
 * @var $dataProvider ActiveDataProvider
 * @var $isAdmin bool
 */

$this->title = 'Спискок компаний';
?>
<div class="site-index">
    <?= GridView::widget(
        [
            'dataProvider' => $dataProvider,
            'columns' => [
                'id',
                'name',
                'inn',
                'general_manager',
                'address',
                [
                    'label' => 'Просмотр',
                    'value' => function ($data) use ($isAdmin) {
                        $text = $isAdmin ? 'Изменить' : 'Просмотреть';
                        return Html::a($text, ['site/update-company','id' => $data->id],
                            ['class' => 'btn btn-success']);
                    },
                    'format' => 'raw',
                ],
            ]
        ]
    ); ?>
</div>

views/site/login.php
<?php

/**
 * @var $this yii\web\View
 * @var $form yii\bootstrap\ActiveForm
 * @var $model app\models\LoginForm
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1'],
        ],
    ]); ?>

        <?= $form->field($model, 'login')->textInput(['autofocus' => true]) ?>
        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/users.php
<?php

use app\models\User;

/* @var $users User[] */

$this->title = 'Список пользователей';
$this->params['breadcrumbs'][] = $this->title;

$menu = [
    ['name' => 'Имя', 'class' => 'login'],
    ['name' => 'Пароль', 'class' => 'password'],
    ['name' => 'Роль', 'class' => 'role'],
    ['name' => '', 'class' => 'change']
];
?>

<h1 class="title"><?= $this->title ?></h1>
<div>
    <div class="row">
        <?php foreach ($menu as $item) : ?>
            <div class="col-3 themed-grid-col"><?= $item['name'] ?></div>
        <?php endforeach; ?>
    </div>
    <?php foreach ($users as $user): ?>
        <div class="row show-user" data-id="<?= $user->id ?>">
            <?php foreach ($menu as $item) { ?>
                <?php if($item['class'] !== 'change') { ?>
                    <div class="col-3 themed-grid-col user-<?= $item['class'] ?>">
                        <?= $item['class'] !== 'role' ? $user->$item['class'] : $user->role->name ?>
                    </div>
                <?php } else { ?>
                    <div class="col-3 themed-grid-col">
                        <button class="btn btn-primary show-update-div" data-id="<?= $user->id ?>">Изменить</button>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
        <div class="row update-user" data-id="<?= $user->id ?>">
            <?php foreach ($menu as $item) { ?>
                <?php if($item['class'] !== 'change') { ?>
                    <div class="col-3 themed-grid-col">
                        <input type="text" class="form-control new-<?= $item['class'] ?>" placeholder="<?= $item['name'] ?>">
                    </div>
                <?php } else { ?>
                    <div class="col-3 themed-grid-col">
                        <button class="btn btn-success save-user-info">Сохранить</button>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
    <?php endforeach; ?>
</div>